#!/bin/bash

# Define constants
MOUNT="m"
UNMOUNT="u"
MOUNTING_PATH="/media/$USER/mbv"
BITLOCKER_PATH="$MOUNTING_PATH/bitlocker"
VOLUME_PATH="$MOUNTING_PATH/volume"

# Mount or unmount
while read -p "Mount or unmount (m/u)? " mountOption
do 

# Mount
if [ $mountOption == $MOUNT ]
then
# Create directory
echo "Creating directories..."
cd /
sudo mkdir -p $BITLOCKER_PATH
sudo mkdir $VOLUME_PATH 

# Read volumes
sudo fdisk -l | grep --color="never" Device -A 19
read -p "Choose directory /dev/: " dir

# Unlock and mount
echo "Unlocking..."
sudo dislocker /dev/$dir -u $BITLOCKER_PATH &&
echo "Mounting..." &&
sudo mount $BITLOCKER_PATH/dislocker-file $VOLUME_PATH &&
echo "Volume mounted!"
break

# Unmount
elif [ $mountOption == $UNMOUNT ]
then
cd ~
echo "Unmounting volume..."
sudo umount $VOLUME_PATH &&
sleep 0.5 &&
sudo umount $BITLOCKER_PATH &&
sleep 0.5 &&
echo "Volume unmounted!"
break
fi

done



